### ISSUE TITLE
User Locales wrong. 

### ISSUE THREAD

**Issue by github-login** [offensive-security/kali-arm-build-scripts#109]
On Acer Chromebook 13 (veyron) : 

```
$ locale
LANG=aa_DJ.utf8
LANGUAGE=
LC_CTYPE="aa_DJ.utf8"
LC_NUMERIC="aa_DJ.utf8"
LC_TIME="aa_DJ.utf8"
LC_COLLATE="aa_DJ.utf8"
LC_MONETARY="aa_DJ.utf8"
LC_MESSAGES="aa_DJ.utf8"
LC_PAPER="aa_DJ.utf8"
LC_NAME="aa_DJ.utf8"
LC_ADDRESS="aa_DJ.utf8"
LC_TELEPHONE="aa_DJ.utf8"
LC_MEASUREMENT="aa_DJ.utf8"
LC_IDENTIFICATION="aa_DJ.utf8"
LC_ALL=
```

```
$ cat /etc/default/locale 
#  File generated by update-locale
LANG=en_GB.UTF-8
```

None of the standard Debian/Linux ways takes effect. 
Please comment. Thank you.

**Comment by steev** [comment]
All of the locales are installed by default, you would do 'dpkg-reconfigure locales' and then apt-get purge locales-all and it will generate only the locale you want after purging the entire history.  

Unfortunately, there seems to be an (upstream) bug in lightdm where it picks the first locale, instead of the user chosen locale.
