### ISSUE TITLE
install chromebook nyan version on hdd

### ISSUE THREAD

**Issue by stuffinator** [offensive-security/kali-arm-build-scripts#155]
I downloaded the "kali-linux-2018.4-nyan" image and could successfully boot from sdcard. Which is nice for a start, but I'm actually more interested in installing kali on hdd and getting rid of chrome-os. However, every tutorial I find suggests that after creating a bootable sdcard or usb and booting from it you'll get prompted with an install boot menu, which doesn't happen for me.
I'm not experienced enough to understand the build script and therefore I can't tell if the boot menu was excluded from this build or not.

So I guess my question is, what options do I have for installing kali on my chromebook hdd?

Any help would be appreciated.

**Comment by steev** [comment]
Installing onto the emmc (hdd) isn't straight forward at all.  You *can* do it, but I don't enable that in the images because of how error prone the process is.  

This would be a topic better covered on the forums, the issue list is more for issues directly related to building the images not help on doing something with a device.
